[package]
name = "autori"
version = "0.1.0"
authors = ["gauthier78 <raphael.gauthier@etu.unilim.fr>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
